### ISSUE TITLE
Multiple messages in a burst

### ISSUE THREAD

**Issue by kitwalker12** [tholman/office-simulator#2]
Today the office manager burst out about 9 messages in a burst.
Is that a bug or a feature?
I'm running this on a docker container. where could I find the logs?

**Comment by TowardsDeath** [comment]
I’ve run into this as well. Not running in a docker container, by the way.

**Comment by tholman** [comment]
3 years later, found this bug. if it was a weekend, it would reset the date to an earlier one... so if you tested this on the 1st to the 7th of each month, it would work, but would go weird outside of that area. -_-
